In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('../data/data.csv')

In [4]:
print(f"données brutes : {df.shape[0]} joueurs et {df.shape[1]} colones")

données brutes : 2761 joueurs et 102 colones

In [5]:
df.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Comp', 'Age', 'Born', 'MP',
       'Starts',
       ...
       'CrdY_stats_misc', 'CrdR_stats_misc', '2CrdY', 'Fls', 'Fld', 'Off',
       'Crs', 'Int', 'TklW', 'OG'],
      dtype='object', length=102)

In [6]:
df.head(2)

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,CrdY_stats_misc,CrdR_stats_misc,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,eng Premier League,25.0,2000.0,33,27,...,2,0,0,19,47,5,36,15,22,0
1,2,Zach Abbott,eng ENG,DF,Nottingham Forest,eng Premier League,19.0,2006.0,2,1,...,0,0,0,2,1,0,3,2,2,0

In [7]:
def audit_data(df):
    report= pd.DataFrame({
        'Type': df.dtypes,
        'Valeurs Nulles': df.isnull().sum(),
        '% Nulles': (df.isnull().sum() / len(df)) * 100,
        'Valeurs Uniques': df.nunique()
    })
    problems = report[(report['Valeurs Nulles'] > 0) | (report['Type'] == 'object')]
    print(problems)
    return report
report=audit_data(df)
print(report)

                              Type  Valeurs Nulles   % Nulles  Valeurs Uniques
Player                      object               0   0.000000             2609
Nation                      object               2   0.072438              113
Pos                         object               0   0.000000                9
Squad                       object               0   0.000000               96
Comp                        object               0   0.000000                5
Age                        float64               1   0.036219               27
Born                       float64               1   0.036219               28
Rk_stats_keeper            float64            2585  93.625498              176
Nation_stats_keeper         object            2585  93.625498               46
Pos_stats_keeper            object            2585  93.625498                1
Comp_stats_keeper           object            2585  93.625498                5
Age_stats_keeper            object            2585  93.625498              174
Born_stats_keeper          float64            2585  93.625498               23
MP_stats_keeper            float64            2585  93.625498               34
Starts_stats_keeper        float64            2585  93.625498               35
Min_stats_keeper           float64            2585  93.625498               82
90s_stats_keeper           float64            2585  93.625498               72
GA                         float64            2585  93.625498               56
GA90                       float64            2585  93.625498               96
SoTA                       float64            2585  93.625498              104
Saves                      float64            2585  93.625498               83
Save%                      float64            2586  93.661717              115
W                          float64            2585  93.625498               24
D                          float64            2585  93.625498               15
L                          float64            2585  93.625498               21
CS                         float64            2585  93.625498               17
CS%                        float64            2588  93.734154               85
PKatt_stats_keeper         float64            2585  93.625498               11
PKA                        float64            2585  93.625498                9
PKsv                       float64            2585  93.625498                4
PKm                        float64            2585  93.625498                4
Nation_stats_shooting       object               2   0.072438              113
Pos_stats_shooting          object               0   0.000000                9
Comp_stats_shooting         object               0   0.000000                5
Age_stats_shooting          object               1   0.036219             2103
Born_stats_shooting        float64               1   0.036219               28
SoT%                       float64             459  16.624411              264
G/Sh                       float64             459  16.624411               37
G/SoT                      float64             802  29.047447               61
Nation_stats_playing_time   object               2   0.072438              113
Pos_stats_playing_time      object               0   0.000000                9
Comp_stats_playing_time     object               0   0.000000                5
Age_stats_playing_time      object               1   0.036219             2103
Born_stats_playing_time    float64               1   0.036219               28
Mn/Start                   float64             336  12.169504               55
Mn/Sub                     float64             390  14.125317               67
On-Off                     float64              37   1.340094              560
Nation_stats_misc           object               2   0.072438              113
Pos_stats_misc              object               0   0.000000                9
Comp_stats_misc             object               0   0.000000                5
Age_stats_misc              object               1   0.036219             2103
Born_stats_misc            float64               1   0.036219               28
          Type  Valeurs Nulles  % Nulles  Valeurs Uniques
Rk       int64               0  0.000000             2761
Player  object               0  0.000000             2609
Nation  object               2  0.072438              113
Pos     object               0  0.000000                9
Squad   object               0  0.000000               96
...        ...             ...       ...              ...
Off      int64               0  0.000000               30
Crs      int64               0  0.000000              161
Int      int64               0  0.000000               55
TklW     int64               0  0.000000               63
OG       int64               0  0.000000                3

[102 rows x 4 columns]

# Suppression des colonnes redondantes générées par le merge

In [8]:
# On identifie toutes les colonnes qui contiennent le mot 'stats' ou 'Born'
cols_to_drop = [c for c in df.columns if 'stats' in c or 'Born' in c]

# On les supprime d'un coup
df_clean = df.drop(columns=cols_to_drop)

# On vérifie le résultat
print(f"Colonnes restantes : {len(df_clean.columns)}")
print(df_clean.columns.tolist())

Colonnes restantes : 61
['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Comp', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'G+A-PK', 'GA', 'GA90', 'SoTA', 'Saves', 'Save%', 'W', 'D', 'L', 'CS', 'CS%', 'PKA', 'PKsv', 'PKm', 'Sh', 'SoT', 'SoT%', 'Sh/90', 'SoT/90', 'G/Sh', 'G/SoT', 'Mn/MP', 'Min%', 'Mn/Start', 'Compl', 'Subs', 'Mn/Sub', 'unSub', 'PPM', 'onG', 'onGA', '+/-', '+/-90', 'On-Off', '2CrdY', 'Fls', 'Fld', 'Off', 'Crs', 'Int', 'TklW', 'OG']

# Exclusion des gardiens de but

In [9]:
df_clean=df_clean[df_clean['Pos']!='GK']

In [10]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2585 entries, 0 to 2760
Data columns (total 61 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Rk        2585 non-null   int64
 1   Player    2585 non-null   object
 2   Nation    2583 non-null   object
 3   Pos       2585 non-null   object
 4   Squad     2585 non-null   object
 5   Comp      2585 non-null   object
 6   Age       2584 non-null   float64
 7   MP        2585 non-null   int64
 8   Starts    2585 non-null   int64
 9   Min       2585 non-null   int64
 10  90s       2585 non-null   float64
 11  Gls       2585 non-null   int64
 12  Ast       2585 non-null   int64
 13  G+A       2585 non-null   int64
 14  G-PK      2585 non-null   int64
 15  PK        2585 non-null   int64
 16  PKatt     2585 non-null   int64
 17  CrdY      2585 non-null   int64
 18  CrdR      2585 non-null   int64
 19  G+A-PK    2585 non-null   float64
 20  GA        0 non-null      float64
 21  GA90      0 non-null      float64
 22  SoTA      0 non-null      float64
 23  Saves     0 non-null      float64
 24  Save%     0 non-null      float64
 25  W         0 non-null      float64
 26  D         0 non-null      float64
 27  L         0 non-null      float64
 28  CS        0 non-null      float64
 29  CS%       0 non-null      float64
 30  PKA       0 non-null      float64
 31  PKsv      0 non-null      float64
 32  PKm       0 non-null      float64
 33  Sh        2585 non-null   int64
 34  SoT       2585 non-null   int64
 35  SoT%      2295 non-null   float64
 36  Sh/90     2585 non-null   float64
 37  SoT/90    2585 non-null   float64
 38  G/Sh      2295 non-null   float64
 39  G/SoT     1958 non-null   float64
 40  Mn/MP     2585 non-null   int64
 41  Min%      2585 non-null   float64
 42  Mn/Start  2252 non-null   float64
 43  Compl     2585 non-null   int64
 44  Subs      2585 non-null   int64
 45  Mn/Sub    2343 non-null   float64
 46  unSub     2585 non-null   int64
 47  PPM       2585 non-null   float64
 48  onG       2585 non-null   int64
 49  onGA      2585 non-null   int64
 50  +/-       2585 non-null   int64
 51  +/-90     2585 non-null   float64
 52  On-Off    2579 non-null   float64
 53  2CrdY     2585 non-null   int64
 54  Fls       2585 non-null   int64
 55  Fld       2585 non-null   int64
 56  Off       2585 non-null   int64
 57  Crs       2585 non-null   int64
 58  Int       2585 non-null   int64
 59  TklW      2585 non-null   int64
 60  OG        2585 non-null   int64
dtypes: float64(27), int64(29), object(5)
memory usage: 1.2+ MB

In [11]:
df_clean.isnull().sum()

Rk        0
Player    0
Nation    2
Pos       0
Squad     0
         ..
Off       0
Crs       0
Int       0
TklW      0
OG        0
Length: 61, dtype: int64

In [12]:
df_clean.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,MP,Starts,Min,...,+/-90,On-Off,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,eng Premier League,25.0,33,27,2220,...,0.28,1.78,0,19,47,5,36,15,22,0
1,2,Zach Abbott,eng ENG,DF,Nottingham Forest,eng Premier League,19.0,2,1,120,...,-3.00,-3.00,0,2,1,0,3,2,2,0
2,3,Jones El-Abdellaoui,ma MAR,"MF,FW",Celta Vigo,es La Liga,20.0,20,4,638,...,0.71,0.82,0,5,3,2,26,3,3,0
3,4,Himad Abdelli,dz ALG,MF,Marseille,fr Ligue 1,26.0,8,1,138,...,-3.91,-4.73,0,3,0,0,1,2,1,0
4,5,Himad Abdelli,dz ALG,MF,Angers,fr Ligue 1,26.0,13,11,943,...,-0.10,0.68,0,16,12,1,9,13,17,0

# Supprime les colonnes où TOUTES les valeurs sont nulles (NaN)

In [13]:

df_clean = df_clean.dropna(axis=1, how='all')

# Vérification immédiate
print(f"Nombre de colonnes après nettoyage automatique : {len(df_clean.columns)}")

Nombre de colonnes après nettoyage automatique : 48

In [14]:
df_clean.head(2)

,Rk,Player,Nation,Pos,Squad,Comp,Age,MP,Starts,Min,...,+/-90,On-Off,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,eng Premier League,25.0,33,27,2220,...,0.28,1.78,0,19,47,5,36,15,22,0
1,2,Zach Abbott,eng ENG,DF,Nottingham Forest,eng Premier League,19.0,2,1,120,...,-3.00,-3.00,0,2,1,0,3,2,2,0

In [15]:
df_clean.shape[0]

2585

In [17]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2585 entries, 0 to 2760
Data columns (total 48 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Rk        2585 non-null   int64
 1   Player    2585 non-null   object
 2   Nation    2583 non-null   object
 3   Pos       2585 non-null   object
 4   Squad     2585 non-null   object
 5   Comp      2585 non-null   object
 6   Age       2584 non-null   float64
 7   MP        2585 non-null   int64
 8   Starts    2585 non-null   int64
 9   Min       2585 non-null   int64
 10  90s       2585 non-null   float64
 11  Gls       2585 non-null   int64
 12  Ast       2585 non-null   int64
 13  G+A       2585 non-null   int64
 14  G-PK      2585 non-null   int64
 15  PK        2585 non-null   int64
 16  PKatt     2585 non-null   int64
 17  CrdY      2585 non-null   int64
 18  CrdR      2585 non-null   int64
 19  G+A-PK    2585 non-null   float64
 20  Sh        2585 non-null   int64
 21  SoT       2585 non-null   int64
 22  SoT%      2295 non-null   float64
 23  Sh/90     2585 non-null   float64
 24  SoT/90    2585 non-null   float64
 25  G/Sh      2295 non-null   float64
 26  G/SoT     1958 non-null   float64
 27  Mn/MP     2585 non-null   int64
 28  Min%      2585 non-null   float64
 29  Mn/Start  2252 non-null   float64
 30  Compl     2585 non-null   int64
 31  Subs      2585 non-null   int64
 32  Mn/Sub    2343 non-null   float64
 33  unSub     2585 non-null   int64
 34  PPM       2585 non-null   float64
 35  onG       2585 non-null   int64
 36  onGA      2585 non-null   int64
 37  +/-       2585 non-null   int64
 38  +/-90     2585 non-null   float64
 39  On-Off    2579 non-null   float64
 40  2CrdY     2585 non-null   int64
 41  Fls       2585 non-null   int64
 42  Fld       2585 non-null   int64
 43  Off       2585 non-null   int64
 44  Crs       2585 non-null   int64
 45  Int       2585 non-null   int64
 46  TklW      2585 non-null   int64
 47  OG        2585 non-null   int64
dtypes: float64(14), int64(29), object(5)
memory usage: 989.6+ KB

In [18]:
df_clean.describe()

,Rk,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,...,+/-90,On-Off,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG
count,2585.000000,2584.000000,2585.000000,2585.000000,2585.000000,2585.000000,2585.000000,2585.000000,2585.000000,2585.000000,...,2585.000000,2579.000000,2585.000000,2585.000000,2585.000000,2585.000000,2585.000000,2585.000000,2585.000000,2585.000000
mean,1371.649903,25.477167,17.545455,12.108317,1086.496712,12.072882,1.623211,1.119149,2.742360,1.468859,...,-0.221807,-0.174847,0.041393,14.270406,13.335783,2.021277,21.304836,9.971760,11.688975,0.042553
std,797.067657,4.495994,10.066668,9.862438,839.754362,9.331658,2.726221,1.707217,3.815218,2.371932,...,4.993199,4.981219,0.203083,12.123398,13.499750,3.556152,32.526304,10.871807,11.320170,0.216680
min,1.000000,16.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-90.000000,-90.030000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,683.000000,22.000000,9.000000,3.000000,311.000000,3.500000,0.000000,0.000000,0.000000,0.000000,...,-0.620000,-0.590000,0.000000,4.000000,3.000000,0.000000,1.000000,1.000000,2.000000,0.000000
50%,1369.000000,25.000000,19.000000,11.000000,961.000000,10.700000,1.000000,0.000000,1.000000,1.000000,...,-0.070000,0.000000,0.000000,12.000000,9.000000,1.000000,8.000000,6.000000,9.000000,0.000000
75%,2056.000000,28.000000,27.000000,20.000000,1784.000000,19.800000,2.000000,2.000000,4.000000,2.000000,...,0.450000,0.540000,0.000000,22.000000,20.000000,2.000000,27.000000,16.000000,18.000000,0.000000
max,2761.000000,42.000000,34.000000,34.000000,3060.000000,34.000000,33.000000,19.000000,38.000000,23.000000,...,90.000000,89.650000,2.000000,75.000000,104.000000,38.000000,274.000000,67.000000,65.000000,2.000000

In [20]:
df_clean.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Comp', 'Age', 'MP', 'Starts',
       'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY',
       'CrdR', 'G+A-PK', 'Sh', 'SoT', 'SoT%', 'Sh/90', 'SoT/90', 'G/Sh',
       'G/SoT', 'Mn/MP', 'Min%', 'Mn/Start', 'Compl', 'Subs', 'Mn/Sub',
       'unSub', 'PPM', 'onG', 'onGA', '+/-', '+/-90', 'On-Off', '2CrdY', 'Fls',
       'Fld', 'Off', 'Crs', 'Int', 'TklW', 'OG'],
      dtype='object')

# Suppression des colonnes spécifiques non pertinentes

In [24]:
cols_to_drop=['Rk','OG','unSub',"Mn/Start"]

df_clean.drop(columns=[c for c in cols_to_drop if c in df_clean.columns], inplace=True)

print(f"Nettoyage terminé. Il reste {len(df_clean.columns)} colonnes.")

Nettoyage terminé. Il reste 44 colonnes.

# Conserver uniquement les joueurs fiables (> 900 minutes)

In [25]:
df_clean=df_clean[df_clean['Min']>=900]

In [34]:
df_clean.isnull().sum()

Player      0
Nation      0
Pos         0
Squad       0
Comp        0
Age         0
MP          0
Starts      0
Min         0
90s         0
Gls         0
Ast         0
G+A         0
G-PK        0
PK          0
PKatt       0
CrdY        0
CrdR        0
G+A-PK      0
Sh          0
SoT         0
SoT%        2
Sh/90       0
SoT/90      0
G/Sh        2
G/SoT      75
Mn/MP       0
Min%        0
Compl       0
Subs        0
Mn/Sub    166
PPM         0
onG         0
onGA        0
+/-         0
+/-90       0
On-Off      6
2CrdY       0
Fls         0
Fld         0
Off         0
Crs         0
Int         0
TklW        0
dtype: int64

# Remplacer les NaN par 0 uniquement pour les variables numériques

In [36]:
# 1. On sélectionne uniquement les colonnes qui contiennent des nombres (int ou float)
numeric_cols = df_clean.select_dtypes(include=['float64', 'int64']).columns

# 2. On remplace les NaN par 0 uniquement dans ces colonnes
df_clean[numeric_cols] = df_clean[numeric_cols].fillna(0)

# 3. Vérification : ça doit afficher 0
print(f"Nombre de valeurs nulles restantes : {df_clean.isnull().sum().sum()}")

Nombre de valeurs nulles restantes : 0

#  FEATURE ENGINEERING (Création des stats Per 90)

In [35]:

cols_to_normalize = ['Gls', 'Ast', 'Sh', 'SoT', 'Int', 'TklW', 'Crs']

for col in cols_to_normalize:

    new_col_name = f"{col}_90"

    df_clean[new_col_name] = (df_clean[col] / df_clean['Min']) * 90


print(df_clean[['Player', 'Gls', 'Gls_90']].head())

             Player  Gls    Gls_90
0  Brenden Aaronson    4  0.162162
4     Himad Abdelli    2  0.190880
5          Ali Abdi    2  0.172249
7   Saud Abdulhamid    2  0.146699
9   Laurent Abergel    1  0.043415

In [39]:
output_file = '../data/football_data_cleaned.csv'
df_clean.to_csv(output_file, index=False)